model:
  name: "/data/hf_models/colpali-v1.2-merged"
  cache_dir: "/data/hf_models/"

device: "cuda:0"

dataset:
  input_path: "/data/hf_datasets/colpali_train_set/"
  output_dir: "/data/hf_datasets/rerank_train_set_colpali_1_2merge_train118659_qdrantdb_bin1/"
  split: "train"
  source: ["tatdqa","pdf"]

db:
  db_path: "/data/hf_datasets/qdrantdb"
  collection_name: "coplali_full_train118659"

batch_size:
  image: 8
  query: 32